### ISSUE TITLE
Customize and add new features to Panel-RIG

### ISSUE THREAD

**Issue by BearBang7** [TheDevFromKer/xmrig-mod#1]
Dear Vlad, i appreciate for your help.

### features I would have in Panel-RIG :

- [x] embedded and hardcoded config.
- [x] encode or encrypt my wallet and pool address.
- [x] i don't need console output, so it's better to hide the console.
- [x] when some proccess running it pause mining, like when i play video game,firefox,**taskmanager**.
- [x] Auto startup as service.
- [x] It protects itself against terminate call, kill and be persistence.

**Comment by TheDevFromKer** [comment]
For hidden autorun use my .bat script.

**Comment by BearBang7** [comment]
@TheDevFromKer I don’t know how to thank you!

**Comment by TheDevFromKer** [comment]
@BearBang7 https://github.com/TheDevFromKer/xmrig-mod#how-to-encrypt - info how to encrypt.
No need thanks, I just like a write code ;-)
