### ISSUE TITLE
Question concerning porting code >> xmrigCC w/ Daemon

### ISSUE THREAD

**Issue by lost-bro** [TheDevFromKer/xmrig-mod#3]
Good day, I appreciate your work on the subject.  I complied your code and it works as advertised.
Had to add a couple more .h files on the 'xmrig.cpp' in order to get it to compile w/o errors on windows 7.
I 'borrowed' some of your ideas, and modified the 'xmrigCC' code from Github (https://github.com/Bendr0id/xmrigCC)  in order to integrate the encryption aspect.   Got it all to compile and the .exe runs, but it does not open/start the Daemon.  Of course it starts the 'miner'.  The deal w/ 'xmrigCC' is that the Daemon must be started and the encryption arguments must be passed to the 'miner'.  So the situation gets complicated quickly.

I would like to hear your ideas on how to make your encryption code pass the arguments >> miner, while starting the 'Daemon', and thanks for releasing your work to the public.

take care, peace
lost_bro

**Comment by TheDevFromKer** [comment]
I no longer update this thread.
