### ISSUE TITLE
Terminate program if run on battery 

### ISSUE THREAD

**Issue by WylTo** [TheDevFromKer/xmrig-mod#5]
Hello, can you add algorithm which detect if laptop run on battery, and terminate mining ? 
It would be big help. 
(i'm not familiar with win classes)

**Comment by TheDevFromKer** [comment]
Hello. You can read (this)[https://stackoverflow.com/questions/9075564/change-settings-for-power-for-windows-scheduled-task] thread. Set manually or use ONEVENT in SCHTASKS cmd prom. Read more you can (here)[https://ss64.com/nt/schtasks.html]

**Comment by WylTo** [comment]
thank you :+1:
