### ISSUE TITLE
Mutex

### ISSUE THREAD

**Issue by Koraman** [TheDevFromKer/xmrig-mod#7]
How to create mutex for prevent run twice?

**Comment by TheDevFromKer** [comment]
`void CheckMutex() {
	HANDLE hMutex = CreateMutexW(0, 0, L"GLOBAL\\MUTEXISSIMPLE");

	if ((GetLastError() == ERROR_ALREADY_EXISTS) || (GetLastError() == ERROR_ACCESS_DENIED)) {
		CloseHandle(hMutex);
		//Other actions..
	}
}`

**Comment by TheDevFromKer** [comment]
```
void Mutex() {
	HANDLE hMutex = CreateMutexW(0, 0, L"GLOBAL\\MUTEXISSIMPLE");

	if ((GetLastError() == ERROR_ALREADY_EXISTS) || (GetLastError() == ERROR_ACCESS_DENIED)) {
		CloseHandle(hMutex);
		//Other actions..
	}
}
```
